# Generated by Django 4.2.15 on 2024-08-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='role',
            field=models.TextField(null=True),
        ),
    ]
