# Generated by Django 4.2.15 on 2024-08-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_data_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='role',
        ),
    ]
