# Generated by Django 4.2.15 on 2024-08-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_data_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='roles',
            field=models.TextField(null=True),
        ),
    ]
