# Generated by Django 4.2.15 on 2024-08-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_data_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
        migrations.AlterField(
            model_name='data',
            name='roles',
            field=models.CharField(max_length=200),
        ),
    ]
