# Generated by Django 4.2.15 on 2024-08-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_data_name_alter_data_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='roles',
        ),
        migrations.AddField(
            model_name='data',
            name='roles',
            field=models.ManyToManyField(to='app.rolename'),
        ),
    ]
