# Generated by Django 4.2.15 on 2024-08-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rolename_remove_data_roles_data_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='roles',
        ),
        migrations.DeleteModel(
            name='RoleName',
        ),
        migrations.AddField(
            model_name='data',
            name='roles',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
