# Generated by Django 4.2.15 on 2024-08-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_data_roles_delete_rolename_data_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='roles',
            field=models.CharField(max_length=100),
        ),
    ]
