# Generated by Django 4.2.15 on 2024-09-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_data_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
